import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { ModalProvider, Modal } from "@/app/(_home)/_context/Modal";
import NavBarShell from "@/app/(_home)/_components/NavBar/NavBarShell";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-screenWhite`}>
        <ModalProvider>
          <Suspense fallback={<div>Loading...</div>}>
            <NavBarShell />
          </Suspense>
          {children}
          <Modal />
        </ModalProvider>
      </body>
    </html>
  );
}
